import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;

import org.xml.sax.SAXException;

public class SalesforceDependencies {
	
	static boolean ignoreCase = true;
	static boolean ignoreTestClass = true;	
	
	static Map itemList = new TreeMap();

    public static void 	writeToCsv(String folderName) throws IOException {
		  FileWriter fw = new FileWriter(folderName+"\\result.csv");
		  
		  System.out.println("Creating file: result.csv");
		  
		  fw.write( "Value,Primary Dependencies, Secondary Dependencies\n" );
		  for(Object item: itemList.keySet()) {
			  String primaryDependencies ="";
			  String secondaryDependencies ="";
			  List<String> dependencies = (List<String>) itemList.get(item.toString());
			  for(String dependency : dependencies)  {
				  //split() accepts a regular expression, so you need to escape . to not consider it as a regex meta character
				  String[] splittedDependency = dependency.split("\\.");
				  System.out.println(item.toString()+ " dependency:" + dependency);
				  String formatedDependency = splittedDependency[1] +": "+ splittedDependency[0]; 
				  if (dependency.toLowerCase().indexOf(".profile") !=-1 ||
					  dependency.toLowerCase().indexOf(".app") !=-1 ||
					  dependency.toLowerCase().indexOf(".permissionset") !=-1) {
					secondaryDependencies = secondaryDependencies + formatedDependency+"\n";					  
				  }
				  else {
					primaryDependencies = primaryDependencies + formatedDependency+"\n";					  
				  }
			  }
			  fw.write( item.toString() + ",\"" + primaryDependencies+"\",\"" + secondaryDependencies+"\"\n" );		  
		  }
		  
		  fw.close();
		  System.out.println("File created");

    }	
	

    public static void 	writeToCsvFlat(String folderName) throws IOException {
		  FileWriter fw = new FileWriter(folderName+"\\resultFlat.csv");
		  
		  System.out.println("Creating file: result.csv");
		  
		  fw.write( "Value,Object Type,Name\n" );
		  for(Object item: itemList.keySet()) {
			  List<String> dependencies = (List<String>) itemList.get(item.toString());
			  for(String dependency : dependencies)  {
				  //split() accepts a regular expression, so you need to escape . to not consider it as a regex meta character
				  String[] splittedDependency = dependency.split("\\.");
				  System.out.println(item.toString() + " dependency:" + dependency);
				  fw.write( item.toString() + ",\"" + splittedDependency[1]+"\",\"" + splittedDependency[0]+"\"\n" );		  
			  }
		  }
		  
		  fw.close();
		  System.out.println("File created");

    }	
    
    
    public static boolean containsText (String searchText, String path, String fileName, boolean ignoreCase) throws IOException, ParserConfigurationException {
		if ((searchText+"").length() ==0) return false;
    	FileReader fr;	
		fr = new FileReader(path+fileName);
		BufferedReader br = new BufferedReader(fr);
		String phisicalLine;
		
		while( (phisicalLine = br.readLine()) != null) {
			if (ignoreCase) 
				phisicalLine = (phisicalLine+"").toUpperCase();
			int positionFound = (phisicalLine+"").indexOf(searchText);
			
			//"City__c" should not be reported as found in a string "ShippingCity__c"
			//if string was found we check is the letter before the string is letter or digit
			//if this example it is the letter "g" so the function returns false.
			if (positionFound > 0) 
			    if (Character.isLetterOrDigit((phisicalLine+"").charAt(positionFound-1)) 
			    		  || ((phisicalLine+"").charAt(positionFound-1)=='.') 
			    		  || ((phisicalLine+"").charAt(positionFound-1)=='_'))   
			    	return false;
			
			if ( positionFound !=-1)
				return true;
		}	
		fr.close();		
		return false;
	}
		
	public static void readFilesFromFolder(String searchText1, String searchText2,final File folder) throws IOException, SAXException, ParserConfigurationException, XPathExpressionException {
    	System.out.println("Processing:" + searchText1);
	    for (final File fileEntry : folder.listFiles()) {
			if (ignoreCase) {
				searchText1 = searchText1.toUpperCase();
				searchText2 = searchText2.toUpperCase();				
			}
	        if (fileEntry.isDirectory()) {
	        	readFilesFromFolder(searchText1, searchText2, fileEntry);
	        } else {
	            	Boolean ignoreThisFile = false;
	            	if (ignoreTestClass){
	            		if ((fileEntry.getName().endsWith(".cls") )	&& containsText("@ISTEST", folder.getPath()+"\\", fileEntry.getName(), true))
	            			ignoreThisFile = true;
	            	}
	            		
	            	if (!ignoreThisFile && 
	            			(containsText(searchText1, folder.getPath()+"\\", fileEntry.getName(), ignoreCase)
	            			||
	            			containsText(searchText2, folder.getPath()+"\\", fileEntry.getName(), ignoreCase)
	            			)
	            		) {
	            		
	            		if ( !itemList.containsKey(searchText1) ) {
		            		List<String> items = new ArrayList<String>();
		            		itemList.put(searchText1, items);	            			
	            		}
	            		
	            		List<String> items = (List<String>) itemList.get(searchText1);
	            		items.add(fileEntry.getName());
	            		
	            	}
	        }
	    }
	}		
	
	public static void main(String[] args) throws XPathExpressionException, IOException, SAXException, ParserConfigurationException {
		ignoreCase = true;
		ignoreTestClass = true;
		
		String folderName = args[0];

		File d = new File (folderName+"\\result.csv");
		d.delete();
		File d2 = new File (folderName+"\\resultFlat.csv");
		d2.delete();

		//Profiles
		readFilesFromFolder("Jenkins User","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - UA","", new File(folderName));
		readFilesFromFolder("Call Center Agent - US","", new File(folderName));
		readFilesFromFolder("JnJ Base- Console","", new File(folderName));
		readFilesFromFolder("JnJ Base- Standard","", new File(folderName));
		readFilesFromFolder("LifeScan Local Admin - US","", new File(folderName));
		readFilesFromFolder("Marketing Manager - US","", new File(folderName));
		readFilesFromFolder("Sales Rep - VALIDATE","", new File(folderName));
		readFilesFromFolder("Partner Community User","", new File(folderName));
		readFilesFromFolder("LFS Finance User","", new File(folderName));
		readFilesFromFolder("LFS Mkts (Channel) User","", new File(folderName));
		readFilesFromFolder("LFS Mkts (ID) User","", new File(folderName));
		readFilesFromFolder("LFS Mkts (Payer) User","", new File(folderName));
		readFilesFromFolder("LifeScan Compliance Team US","", new File(folderName));
		readFilesFromFolder("LifeScan Contract Local Admin US","", new File(folderName));
		readFilesFromFolder("LifeScan Contract Team Manager US","", new File(folderName));
		readFilesFromFolder("LifeScan Contract Team US","", new File(folderName));
		readFilesFromFolder("LifeScan Customer Services","", new File(folderName));
		readFilesFromFolder("System Admin - No IP Range","", new File(folderName));
		readFilesFromFolder("Animas Sales Rep - France","", new File(folderName));
		readFilesFromFolder("Animas Sales Rep - Germany","", new File(folderName));
		readFilesFromFolder("Animas Sales Rep - Netherlands","", new File(folderName));
		readFilesFromFolder("Animas+Lifescan Sales Rep - France","", new File(folderName));
		readFilesFromFolder("CPC Community Trainer","", new File(folderName));
		readFilesFromFolder("Patient Training Portal Profile","", new File(folderName));
		readFilesFromFolder("CS Agent - Canada","", new File(folderName));
		readFilesFromFolder("CS Agent - China","", new File(folderName));
		readFilesFromFolder("CS Agent - Hong Kong","", new File(folderName));
		readFilesFromFolder("CS Agent - India","", new File(folderName));
		readFilesFromFolder("CS Agent - Indonesia","", new File(folderName));
		readFilesFromFolder("CS Agent - Malaysia","", new File(folderName));
		readFilesFromFolder("CS Agent - North Korea","", new File(folderName));
		readFilesFromFolder("CS Agent - Philippines","", new File(folderName));
		readFilesFromFolder("CS Agent - Singapore","", new File(folderName));
		readFilesFromFolder("CS Agent - South Korea","", new File(folderName));
		readFilesFromFolder("CS Agent - Taiwan","", new File(folderName));
		readFilesFromFolder("CS Agent - Thailand","", new File(folderName));
		readFilesFromFolder("CS Agent - Vietnam","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Canada","", new File(folderName));
		readFilesFromFolder("Canada Tender Manager","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - CN","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - HK","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - ID","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - IN","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - KP","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - KR","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - MY","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - PI","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - SG","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - TH","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - TW","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - VN","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - SK","", new File(folderName));
		readFilesFromFolder("Animas+Lifescan Sales Rep - Netherlands","", new File(folderName));
		readFilesFromFolder("Integration User","", new File(folderName));
		readFilesFromFolder("api_user_mc_NA","", new File(folderName));
		readFilesFromFolder("api_user_mc_ASPAC","", new File(folderName));
		readFilesFromFolder("api_user_mc_EMEA","", new File(folderName));
		readFilesFromFolder("api_user_mc_LATAM","", new File(folderName));
		readFilesFromFolder("System Administrator","", new File(folderName));
		readFilesFromFolder("Standard User","", new File(folderName));
		readFilesFromFolder("Read Only","", new File(folderName));
		readFilesFromFolder("Solution Manager","", new File(folderName));
		readFilesFromFolder("Marketing User","", new File(folderName));
		readFilesFromFolder("Contract Manager","", new File(folderName));
		readFilesFromFolder("Chatter Free User","", new File(folderName));
		readFilesFromFolder("Chatter Moderator User","", new File(folderName));
		readFilesFromFolder("Authenticated Website","", new File(folderName));
		readFilesFromFolder("Standard Platform User","", new File(folderName));
		readFilesFromFolder("Guest License User","", new File(folderName));
		readFilesFromFolder("Chatter External User","", new File(folderName));
		readFilesFromFolder("JnJ Sales","", new File(folderName));
		readFilesFromFolder("External DSA Agent","", new File(folderName));
		readFilesFromFolder("Force.com - One App User","", new File(folderName));
		readFilesFromFolder("JnJ Sales User - One App","", new File(folderName));
		readFilesFromFolder("Benelux Tender Manager","", new File(folderName));
		readFilesFromFolder("Italy Tender Manager","", new File(folderName));
		readFilesFromFolder("MEA Tender Manager","", new File(folderName));
		readFilesFromFolder("Russia Tender Manager","", new File(folderName));
		readFilesFromFolder("Spain Tender Manager","", new File(folderName));
		readFilesFromFolder("UK Tender Manager","", new File(folderName));
		readFilesFromFolder("DSA and Tenders","", new File(folderName));
		readFilesFromFolder("Saudi Arabia Tender Manager","", new File(folderName));
		readFilesFromFolder("Migration","", new File(folderName));
		readFilesFromFolder("UAT Tester","", new File(folderName));
		readFilesFromFolder("Sales Rep - Germany","", new File(folderName));
		readFilesFromFolder("Sales Rep - France","", new File(folderName));
		readFilesFromFolder("Sales Rep - Algeria","", new File(folderName));
		readFilesFromFolder("Sales Rep - Russia","", new File(folderName));
		readFilesFromFolder("Marketing Administrator","", new File(folderName));
		readFilesFromFolder("Interface User","", new File(folderName));
		readFilesFromFolder("Uganda Tender Manager","", new File(folderName));
		readFilesFromFolder("CS Agent Template","", new File(folderName));
		readFilesFromFolder("CS Agent - UK","", new File(folderName));
		readFilesFromFolder("CS ISO Agent Template","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - UK","", new File(folderName));
		readFilesFromFolder("CS Agent - UAE","", new File(folderName));
		readFilesFromFolder("CS Agent - Austria","", new File(folderName));
		readFilesFromFolder("CS Agent - Australia","", new File(folderName));
		readFilesFromFolder("CS Agent - Belgium","", new File(folderName));
		readFilesFromFolder("CS Agent - Bulgaria","", new File(folderName));
		readFilesFromFolder("CS Agent - Belarus","", new File(folderName));
		readFilesFromFolder("CS Agent - Switzerland","", new File(folderName));
		readFilesFromFolder("CS Agent - Czech Republic","", new File(folderName));
		readFilesFromFolder("CS Agent - Germany","", new File(folderName));
		readFilesFromFolder("CS Agent - Denmark","", new File(folderName));
		readFilesFromFolder("CS Agent - Algeria","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - UAE","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Belgium","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Austria","", new File(folderName));
		readFilesFromFolder("CS Agent - EMEA Other","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Australia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Bulgaria","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Belarus","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Switzerland","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Czech Republic","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Germany","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Denmark","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Algeria","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - EMEA Other","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Spain","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Finland","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - France","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Greece","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Croatia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Hungary","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Ireland","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Italy","", new File(folderName));
		readFilesFromFolder("CS Agent - Spain","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Kazakhstan","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Luxembourg","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Netherlands","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Norway","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Poland","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Portugal","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Qatar","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Romania","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Russia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Sweden","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Slovenia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Slovakia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Turkey","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Ukraine","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - South Africa","", new File(folderName));
		readFilesFromFolder("CS Agent - Finland","", new File(folderName));
		readFilesFromFolder("CS Agent - France","", new File(folderName));
		readFilesFromFolder("CS Agent - Greece","", new File(folderName));
		readFilesFromFolder("CS Agent - Croatia","", new File(folderName));
		readFilesFromFolder("CS Agent - Hungary","", new File(folderName));
		readFilesFromFolder("CS Agent - Ireland","", new File(folderName));
		readFilesFromFolder("CS Agent - Italy","", new File(folderName));
		readFilesFromFolder("CS Agent - Kazakhstan","", new File(folderName));
		readFilesFromFolder("CS Agent - Luxembourg","", new File(folderName));
		readFilesFromFolder("CS Agent - Netherlands","", new File(folderName));
		readFilesFromFolder("CS Agent - Norway","", new File(folderName));
		readFilesFromFolder("CS Agent - Portugal","", new File(folderName));
		readFilesFromFolder("CS Agent - Qatar","", new File(folderName));
		readFilesFromFolder("CS Agent - Romania","", new File(folderName));
		readFilesFromFolder("CS Agent - Russia","", new File(folderName));
		readFilesFromFolder("CS Agent - Sweden","", new File(folderName));
		readFilesFromFolder("CS Agent - Slovenia","", new File(folderName));
		readFilesFromFolder("CS Agent - Slovakia","", new File(folderName));
		readFilesFromFolder("CS Agent - Turkey","", new File(folderName));
		readFilesFromFolder("CS Agent - Ukraine","", new File(folderName));
		readFilesFromFolder("CS Agent - South Africa","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator Template","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - AT","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - AE","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - AU","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - BE","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - BG","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - CH","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - PL","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - HU","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - RO","", new File(folderName));
		readFilesFromFolder("Marketing Manager","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - ZA","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - CZ","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - DK","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - DZ","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - FI","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - GR","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - HR","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - LU","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - NL","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - NO","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - QA","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - SE","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - SI","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - TR","", new File(folderName));
		readFilesFromFolder("CS Agent - Poland","", new File(folderName));
		readFilesFromFolder("External Dealer","", new File(folderName));
		readFilesFromFolder("System Administrator with Encryption Off","", new File(folderName));
		readFilesFromFolder("JnJ Project Room","", new File(folderName));
		readFilesFromFolder("Lifescan Site Profile","", new File(folderName));
		readFilesFromFolder("Customer Community Login User","", new File(folderName));
		readFilesFromFolder("Sales Rep - Saudi Arabia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Oman","", new File(folderName));
		readFilesFromFolder("Sales Rep - Bahrain","", new File(folderName));
		readFilesFromFolder("Sales Rep - United Arab Emirates","", new File(folderName));
		readFilesFromFolder("Sales Rep - Qatar","", new File(folderName));
		readFilesFromFolder("Sales Rep - Kuwait","", new File(folderName));
		readFilesFromFolder("Sales Rep - Egypt","", new File(folderName));
		readFilesFromFolder("Sales Rep - Italy","", new File(folderName));
		readFilesFromFolder("CS Agent - Saudi Arabia","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Saudi Arabia","", new File(folderName));
		readFilesFromFolder("Warehouse Administrator - SA","", new File(folderName));
		readFilesFromFolder("CS Agent - Egypt","", new File(folderName));
		readFilesFromFolder("CS Agent - Israel","", new File(folderName));
		readFilesFromFolder("CS Agent - Jordan","", new File(folderName));
		readFilesFromFolder("CS Agent - Kuwait","", new File(folderName));
		readFilesFromFolder("CS Agent - Lebanon","", new File(folderName));
		readFilesFromFolder("CS Agent - Oman","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Egypt","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Israel","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Jordan","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - KW","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Lebanon","", new File(folderName));
		readFilesFromFolder("CS ISO Agent - Oman","", new File(folderName));
		readFilesFromFolder("CS Agent- Bahrain","", new File(folderName));
		readFilesFromFolder("CS ISO Agent- Bahrain","", new File(folderName));
		readFilesFromFolder("Sales Rep - Belgium","", new File(folderName));
		readFilesFromFolder("Sales Rep - Austria","", new File(folderName));
		readFilesFromFolder("Sales Rep - Switzerland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Czech Republic","", new File(folderName));
		readFilesFromFolder("Sales Rep - Denmark","", new File(folderName));
		readFilesFromFolder("Sales Rep - Finland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Greece","", new File(folderName));
		readFilesFromFolder("Sales Rep - Croatia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Luxembourg","", new File(folderName));
		readFilesFromFolder("Sales Rep - Netherlands","", new File(folderName));
		readFilesFromFolder("Sales Rep - Norway","", new File(folderName));
		readFilesFromFolder("Sales Rep - Poland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Sweden","", new File(folderName));
		readFilesFromFolder("Sales Rep - Slovenia","", new File(folderName));
		readFilesFromFolder("Sales Rep - South Africa","", new File(folderName));
		readFilesFromFolder("Sales Rep - Spain","", new File(folderName));
		readFilesFromFolder("Sales Rep - UK","", new File(folderName));
		readFilesFromFolder("Sales Rep - Ireland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Israel","", new File(folderName));
		readFilesFromFolder("Sales Rep - Jordan","", new File(folderName));
		readFilesFromFolder("Sales Rep - Kazakhstan","", new File(folderName));
		readFilesFromFolder("Sales Rep - Lebanon","", new File(folderName));
		readFilesFromFolder("Sales Rep - Portugal","", new File(folderName));
		readFilesFromFolder("Sales Rep - Slovakia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Ukraine","", new File(folderName));
		readFilesFromFolder("Lifescan B2C Community Profile","", new File(folderName));
		readFilesFromFolder("customers Profile","", new File(folderName));
		readFilesFromFolder("CS Agent - Latin America","", new File(folderName));
		readFilesFromFolder("Super User","", new File(folderName));
		readFilesFromFolder("JJDS Standard User","", new File(folderName));
		readFilesFromFolder("Sales Rep - Albania","", new File(folderName));
		readFilesFromFolder("Sales Rep - Armenia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Azerbaijan","", new File(folderName));
		readFilesFromFolder("Sales Rep - Bosnia and Herzegovina","", new File(folderName));
		readFilesFromFolder("Sales Rep - Botswana","", new File(folderName));
		readFilesFromFolder("Sales Rep - Bulgaria","", new File(folderName));
		readFilesFromFolder("Sales Rep - Cyprus","", new File(folderName));
		readFilesFromFolder("Sales Rep - Eritrea","", new File(folderName));
		readFilesFromFolder("Sales Rep - Georgia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Ghana","", new File(folderName));
		readFilesFromFolder("Sales Rep - Hungary","", new File(folderName));
		readFilesFromFolder("Sales Rep - Iceland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Iraq","", new File(folderName));
		readFilesFromFolder("Sales Rep - Kenya","", new File(folderName));
		readFilesFromFolder("Sales Rep - Lesotho","", new File(folderName));
		readFilesFromFolder("Sales Rep - Libya","", new File(folderName));
		readFilesFromFolder("Sales Rep - Lithuania","", new File(folderName));
		readFilesFromFolder("Sales Rep - Macedonia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Malta","", new File(folderName));
		readFilesFromFolder("Sales Rep - Morocco","", new File(folderName));
		readFilesFromFolder("Sales Rep - Namibia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Pakistan","", new File(folderName));
		readFilesFromFolder("Sales Rep - Romania","", new File(folderName));
		readFilesFromFolder("Sales Rep - Senegal","", new File(folderName));
		readFilesFromFolder("Sales Rep - Swaziland","", new File(folderName));
		readFilesFromFolder("Sales Rep - Tanzania","", new File(folderName));
		readFilesFromFolder("Sales Rep - Tunisia","", new File(folderName));
		readFilesFromFolder("Sales Rep - Turkey","", new File(folderName));
		readFilesFromFolder("Sales Rep - Uganda","", new File(folderName));
		readFilesFromFolder("Sales Rep - Zimbabwe","", new File(folderName));
		readFilesFromFolder("Premier Support User","", new File(folderName));
		
		
//		//permission sets
//		readFilesFromFolder("Animas","Animas", new File(folderName));
//		readFilesFromFolder("Animas_Data_Migration","Animas Data Migration", new File(folderName));
//		readFilesFromFolder("Animas_Data_Ops","Animas Data Ops", new File(folderName));
//		readFilesFromFolder("Animas_Manager","Animas Manager", new File(folderName));
//		readFilesFromFolder("Animas_Regional_Business_Manager","Animas Regional Business Manager", new File(folderName));
//		readFilesFromFolder("Animas_Sales_Ops","Animas Sales Ops", new File(folderName));
//		readFilesFromFolder("Animas_US_Delete_Licenses","Animas US Delete Licenses", new File(folderName));
//		readFilesFromFolder("ANM_Inside_Sales_User","ANM: Inside Sales User", new File(folderName));
//		readFilesFromFolder("ANM_PEC_User","ANM: PEC User", new File(folderName));
//		readFilesFromFolder("ASPAC_Data_Viewer","ASPAC Data Viewer", new File(folderName));
//		readFilesFromFolder("Butterfly_BGA","Butterfly BGA", new File(folderName));
//		readFilesFromFolder("Butterfly_BGM","Butterfly BGM", new File(folderName));
//		readFilesFromFolder("Butterfly_CBM","Butterfly CBM", new File(folderName));
//		readFilesFromFolder("Butterfly_PEC","Butterfly PEC", new File(folderName));
//		readFilesFromFolder("ButterflyAdmin","Butterfly Admin", new File(folderName));
//		readFilesFromFolder("Call_Activity_Permissions","Call Activity Permissions", new File(folderName));
//		readFilesFromFolder("Campaign_Analyst","Campaign Analyst", new File(folderName));
//		readFilesFromFolder("Campaign_and_Campaign_Member_View","Campaign and Campaign Member View", new File(folderName));
//		readFilesFromFolder("CBM_Animas","CBM (Animas)", new File(folderName));
//		readFilesFromFolder("Cegedim_Fields_Access","Cegedim Fields Access", new File(folderName));
//		readFilesFromFolder("Copy_Paste_Tool","Copy Paste Tool", new File(folderName));
//		readFilesFromFolder("Create_and_Edit_Dashboards","Create and Edit Dashboards", new File(folderName));
//		readFilesFromFolder("CS_Product_Admin","CS Product Admin", new File(folderName));
//		readFilesFromFolder("CS_Warranty_Card_Access","CS Warranty Card Access", new File(folderName));
//		readFilesFromFolder("Customer_Service_Prague","Customer Service- Prague", new File(folderName));
//		readFilesFromFolder("Customer_Service_Web_Orders","Customer Service Web Orders", new File(folderName));
//		readFilesFromFolder("Customer_Service_WOP","Customer Service WOP", new File(folderName));
//		readFilesFromFolder("Customize_Application","Customize Application", new File(folderName));
//		readFilesFromFolder("Data_Administrator","Data Administrator", new File(folderName));
//		readFilesFromFolder("Data_Loader_Access","Data Loader Access", new File(folderName));
//		readFilesFromFolder("Drupal_Integration_Users","Drupal Integration Users", new File(folderName));
//		readFilesFromFolder("DSA_Administrator","DSA Administrator", new File(folderName));
//		readFilesFromFolder("DSA_Management","DSA Management", new File(folderName));
//		readFilesFromFolder("DSA_User","DSA_User", new File(folderName));
//		readFilesFromFolder("DSA_Users","DSA Users", new File(folderName));
//		readFilesFromFolder("Edit_Reports","Edit Reports", new File(folderName));
//		readFilesFromFolder("Email_Templates_Admin","Email Template Admin", new File(folderName));
//		readFilesFromFolder("EMEA_Coaching_Report","EMEA Coaching Report", new File(folderName));
//		readFilesFromFolder("Enable_Non_Clinical_Stakeholders","Enable Non Clinical Stakeholders", new File(folderName));
//		readFilesFromFolder("ExactTarget","ExactTarget", new File(folderName));
//		readFilesFromFolder("ExactTarget_Integration","Marketing Cloud Connector", new File(folderName));
//		readFilesFromFolder("ExactTarget_Integration_Admin","Marketing Cloud Connector Admin", new File(folderName));
//		readFilesFromFolder("Full_Access_To_Brick","Full Access To Brick", new File(folderName));
//		readFilesFromFolder("Grant_Metrics_on_Event","Grant Metrics on Event", new File(folderName));
//		readFilesFromFolder("Hard_Delete","Bulk API Hard Delete", new File(folderName));
//		readFilesFromFolder("HelpAdministrator","Help Administrator", new File(folderName));
//		readFilesFromFolder("HelpAnalyst","Help Analyst", new File(folderName));
//		readFilesFromFolder("HelpAuthor","Help Author", new File(folderName));
//		readFilesFromFolder("HelpedUser","Helped User", new File(folderName));
//		readFilesFromFolder("ImportWarrantyCards","Import Warranty Cards", new File(folderName));
//		readFilesFromFolder("India_Campaign_Member_PS_Temp","India- Campaign Member PS-Temp", new File(folderName));
//		readFilesFromFolder("Jnj_Base_Standard","Jnj Base Standard", new File(folderName));
//		readFilesFromFolder("Key_Account_Manager","Key Account Manager", new File(folderName));
//		readFilesFromFolder("Language_Translators","Language Translators", new File(folderName));
//		readFilesFromFolder("Lead_Access_Permissions","Lead Access Permissions", new File(folderName));
//		readFilesFromFolder("Lead_Read_Access","Lead Read Access", new File(folderName));
//		readFilesFromFolder("LifeScan_Admin","LifeScan Admin", new File(folderName));
//		readFilesFromFolder("LockdownAddressChanges","LockdownAddressChanges", new File(folderName));
//		readFilesFromFolder("Manage_Cases_Permission","Manage Cases Permission", new File(folderName));
//		readFilesFromFolder("Manage_Dynamic_Dashboards","Manage Dynamic Dashboards", new File(folderName));
//		readFilesFromFolder("Manage_Marketing_Campaign_AP","Manage Marketing Campaign AP", new File(folderName));
//		readFilesFromFolder("Marketing_Cloud_Connected_App","Marketing Cloud Connected App", new File(folderName));
//		readFilesFromFolder("Marketing_Cloud_System_User","Marketing Cloud System User", new File(folderName));
//		readFilesFromFolder("Merge_Accounts_Issue_4949","Merge Accounts Issue 4949", new File(folderName));
//		readFilesFromFolder("MIDAS_access_for_ISO_Profiles","MIDAS access for ISO Profiles", new File(folderName));
//		readFilesFromFolder("MM_DSA_App","MM DSA App", new File(folderName));
//		readFilesFromFolder("Notice_Owner","Notice Owner", new File(folderName));
//		readFilesFromFolder("Notice_Recipient","Notice Recipient", new File(folderName));
//		readFilesFromFolder("NoticeBoard_Administrator","NoticeBoard Administrator", new File(folderName));
//		readFilesFromFolder("NoticeBoard_Owner","NoticeBoard Owner", new File(folderName));
//		readFilesFromFolder("NS_Diag_Tool","Northstar Diagnostics Tool", new File(folderName));
//		readFilesFromFolder("OrdersTab","OrdersTab", new File(folderName));
//		readFilesFromFolder("Password_Never_Expire","Password Never Expire", new File(folderName));
//		readFilesFromFolder("PCA_Permission","PCA Permission", new File(folderName));
//		readFilesFromFolder("Product_permissions","Product permissions", new File(folderName));
//		readFilesFromFolder("Project_Room_End_User_Permission_Set","Project Room End User Permission Set", new File(folderName));
//		readFilesFromFolder("Promotion_Permission_Set","Promotion Permission Set", new File(folderName));
//		readFilesFromFolder("Raise_Sales_Orders_DE","Raise Sales Orders - DE", new File(folderName));
//		readFilesFromFolder("Regional_Business_Manager","Regional Business Manager", new File(folderName));
//		readFilesFromFolder("RU_Agents_Order_UPS_Tracking","RU Agents Order UPS Tracking", new File(folderName));
//		readFilesFromFolder("Run_Reports","Run Reports", new File(folderName));
//		readFilesFromFolder("Sales_Ops","Sales Ops", new File(folderName));
//		readFilesFromFolder("Sales_Rep_Germany_Upgrade_Permissions","Sales Rep Germany Upgrade Permissions", new File(folderName));
//		readFilesFromFolder("Sales_User_AE","Sales User - AE", new File(folderName));
//		readFilesFromFolder("Sales_User_BE","Sales User - BE", new File(folderName));
//		readFilesFromFolder("Sales_User_BH","Sales User - BH", new File(folderName));
//		readFilesFromFolder("Sales_User_DE","Sales User - DE", new File(folderName));
//		readFilesFromFolder("Sales_User_DZ","Sales User - DZ", new File(folderName));
//		readFilesFromFolder("Sales_User_EG","Sales User - EG", new File(folderName));
//		readFilesFromFolder("Sales_User_Exc_RU","Sales User (Exc RU)", new File(folderName));
//		readFilesFromFolder("Sales_User_FR","Sales User - FR", new File(folderName));
//		readFilesFromFolder("Sales_User_GB","Sales User - GB", new File(folderName));
//		readFilesFromFolder("Sales_User_IT","Sales User - IT", new File(folderName));
//		readFilesFromFolder("Sales_User_KW","Sales User - KW", new File(folderName));
//		readFilesFromFolder("Sales_User_OM","Sales User - OM", new File(folderName));
//		readFilesFromFolder("Sales_User_PL","Sales User - PL", new File(folderName));
//		readFilesFromFolder("Sales_User_QA","Sales User - QA", new File(folderName));
//		readFilesFromFolder("Sales_User_RU","Sales User - RU", new File(folderName));
//		readFilesFromFolder("Sales_User_SA","Sales User - SA", new File(folderName));
//		readFilesFromFolder("Sales_User_Validate","Sales User Validate", new File(folderName));
//		readFilesFromFolder("SalesConsoleUser","Salesforce Console User", new File(folderName));
//		readFilesFromFolder("Schedule_Dashboards","Schedule Dashboards", new File(folderName));
//		readFilesFromFolder("SDocs_Administrator","SDocs Administrator", new File(folderName));
//		readFilesFromFolder("SDocs_User","SDocs User", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader","Service Team Leader", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Canada","Service Team Leader Canada", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_China","Service Team Leader China", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Hong_Kong","Service Team Leader Hong Kong", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_India","Service Team Leader India", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Indonesia","Service Team Leader Indonesia", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Malaysia","Service Team Leader Malaysia", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_North_Korea","Service Team Leader North Korea", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Philippines","Service Team Leader Philippines", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Singapore","Service Team Leader Singapore", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_South_Korea","Service Team Leader South Korea", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Taiwan","Service Team Leader Taiwan", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Thailand","Service Team Leader Thailand", new File(folderName));
//		readFilesFromFolder("Service_Team_Leader_Vietnam","Service Team Leader Vietnam", new File(folderName));
//		readFilesFromFolder("Service_User_BH","Service User - BH", new File(folderName));
//		readFilesFromFolder("Service_User_DE","Service User - DE", new File(folderName));
//		readFilesFromFolder("Service_User_DZ","Service User - DZ", new File(folderName));
//		readFilesFromFolder("Service_User_EG","Service User - EG", new File(folderName));
//		readFilesFromFolder("Service_User_FR","Service User - FR", new File(folderName));
//		readFilesFromFolder("Service_User_GB","Service User - GB", new File(folderName));
//		readFilesFromFolder("Service_User_IL","Service User - IL", new File(folderName));
//		readFilesFromFolder("Service_User_JO","Service User - JO", new File(folderName));
//		readFilesFromFolder("Service_User_KW","Service User - KW", new File(folderName));
//		readFilesFromFolder("Service_User_KZ","Service User - KZ", new File(folderName));
//		readFilesFromFolder("Service_User_LB","Service User - LB", new File(folderName));
//		readFilesFromFolder("Service_User_OM","Service User - OM", new File(folderName));
//		readFilesFromFolder("Service_User_PL","Service User - PL", new File(folderName));
//		readFilesFromFolder("Service_User_RU","Service User - RU", new File(folderName));
//		readFilesFromFolder("Service_User_SA","Service User - SA", new File(folderName));
//		readFilesFromFolder("Service_Users_AE","Service Users - AE", new File(folderName));
//		readFilesFromFolder("Service_Users_AT","Service Users - AT", new File(folderName));
//		readFilesFromFolder("Service_Users_AU","Service Users - AU", new File(folderName));
//		readFilesFromFolder("Service_Users_BE","Service Users - BE", new File(folderName));
//		readFilesFromFolder("Service_Users_BG","Service Users - BG", new File(folderName));
//		readFilesFromFolder("Service_Users_BY","Service Users - BY", new File(folderName));
//		readFilesFromFolder("Service_Users_CH","Service Users - CH", new File(folderName));
//		readFilesFromFolder("Service_Users_CZ","Service Users - CZ", new File(folderName));
//		readFilesFromFolder("Service_Users_DK","Service Users - DK", new File(folderName));
//		readFilesFromFolder("Service_Users_EMEA_Other","Service Users - EMEA Other", new File(folderName));
//		readFilesFromFolder("Service_Users_ES","Service Users - ES", new File(folderName));
//		readFilesFromFolder("Service_Users_FI","Service Users - FI", new File(folderName));
//		readFilesFromFolder("Service_Users_GR","Service Users - GR", new File(folderName));
//		readFilesFromFolder("Service_Users_HR","Service Users - HR", new File(folderName));
//		readFilesFromFolder("Service_Users_HU","Service Users - HU", new File(folderName));
//		readFilesFromFolder("Service_Users_IE","Service Users - IE", new File(folderName));
//		readFilesFromFolder("Service_Users_IT","Service Users - IT", new File(folderName));
//		readFilesFromFolder("Service_Users_LU","Service Users - LU", new File(folderName));
//		readFilesFromFolder("Service_Users_NL","Service Users - NL", new File(folderName));
//		readFilesFromFolder("Service_Users_NO","Service Users - NO", new File(folderName));
//		readFilesFromFolder("Service_Users_PT","Service Users - PT", new File(folderName));
//		readFilesFromFolder("Service_Users_QA","Service Users - QA", new File(folderName));
//		readFilesFromFolder("Service_Users_RO","Service Users - RO", new File(folderName));
//		readFilesFromFolder("Service_Users_SA","Service Users - SA", new File(folderName));
//		readFilesFromFolder("Service_Users_SE","Service Users - SE", new File(folderName));
//		readFilesFromFolder("Service_Users_SI","Service Users - SI", new File(folderName));
//		readFilesFromFolder("Service_Users_SK","Service Users - SK", new File(folderName));
//		readFilesFromFolder("Service_Users_TR","Service Users - TR", new File(folderName));
//		readFilesFromFolder("Service_Users_UA","Service Users - UA", new File(folderName));
//		readFilesFromFolder("Service_Users_ZA","Service Users - ZA", new File(folderName));
//		readFilesFromFolder("SFDC_Perm_Set","SFDC Perm Set", new File(folderName));
//		readFilesFromFolder("SFDC_TEST_Event_Invitee","SFDC TEST(Event Invitee)", new File(folderName));
//		readFilesFromFolder("Strategic_Affairs","Strategic Affairs", new File(folderName));
//		readFilesFromFolder("Strategic_Affairs_Administrator","Strategic Affairs Administrator", new File(folderName));
//		readFilesFromFolder("Survey_Viewer","Survey Viewer", new File(folderName));
//		readFilesFromFolder("TBM_Animas","TBM (Animas)", new File(folderName));
//		readFilesFromFolder("Tender_Admin","Tender Admin", new File(folderName));
//		readFilesFromFolder("Tender_Management","UNUSED - Tender Management", new File(folderName));
//		readFilesFromFolder("Tender_Playbook","Tender Playbook", new File(folderName));
//		readFilesFromFolder("TenderPlaybook","Obsolete_TenderPlaybook", new File(folderName));
//		readFilesFromFolder("Test_Accounts_Developer","Test Accounts Developer", new File(folderName));
//		readFilesFromFolder("UAT_Sales_Permission_Set","UAT Sales Permission Set", new File(folderName));
//		readFilesFromFolder("US_Sales_Records","US- Sales Records", new File(folderName));
//		readFilesFromFolder("User_Management","User Management", new File(folderName));
//		readFilesFromFolder("View_Encrypted_Data","View Encrypted Data", new File(folderName));
//		readFilesFromFolder("View_Setup_Configuration","View Setup & Configuration", new File(folderName));
//		readFilesFromFolder("Warehouse_Administrator","Warehouse Administrator", new File(folderName));
//		readFilesFromFolder("Warehouse_Export_Reports","Warehouse Export Reports", new File(folderName));
//		readFilesFromFolder("Warehouse_Log_Warranty_Cards","Warehouse - Log Warranty Cards", new File(folderName));
		
		//readFilesFromFolder("@future", new File(folderName));
		//readFilesFromFolder("@istest", new File(folderName));
		//readFilesFromFolder("@RestResource", new File(folderName));
		//readFilesFromFolder("webService ", new File(folderName));
		//readFilesFromFolder("Batchable", new File(folderName));
		//readFilesFromFolder("Schedulable", new File(folderName));
		//readFilesFromFolder("Messaging.", new File(folderName));		
		
//		readFilesFromFolder("ANI_State_Codes__c", new File(folderName));
//		readFilesFromFolder("APMarkerSetting__c", new File(folderName));
//		readFilesFromFolder("Access_Contracting__c", new File(folderName));
//		readFilesFromFolder("AccountContractValidationMatrix__c", new File(folderName));
//		readFilesFromFolder("Account_Address__c", new File(folderName));
//		readFilesFromFolder("Account_Attributes__c", new File(folderName));
//		readFilesFromFolder("Account_Growth_Initiatives_Meas__c", new File(folderName));
//		readFilesFromFolder("Account_Product__c", new File(folderName));
//		readFilesFromFolder("Account_Sharing_Groups__c", new File(folderName));
//		readFilesFromFolder("Administrators__c", new File(folderName));
//		readFilesFromFolder("AllowableMarket__c", new File(folderName));
//		readFilesFromFolder("AnimasOrder__c", new File(folderName));
//		readFilesFromFolder("AnimasUserEmails__c", new File(folderName));
//		readFilesFromFolder("Animas_Settings__c", new File(folderName));
//		readFilesFromFolder("Approval_Process_Settings__c", new File(folderName));
//		readFilesFromFolder("Assessment__c", new File(folderName));
//		readFilesFromFolder("BG_Chart__c", new File(folderName));
//		readFilesFromFolder("BRICK_Operative__c", new File(folderName));
//		readFilesFromFolder("Books_of_Business__c", new File(folderName));
//		readFilesFromFolder("Bricks__c", new File(folderName));
//		readFilesFromFolder("Budget_Promotion__c", new File(folderName));
//		readFilesFromFolder("Budget__c", new File(folderName));
//		readFilesFromFolder("Busy_Training__c", new File(folderName));
//		readFilesFromFolder("Buying_Influences_Customer_Mtgs__c", new File(folderName));
//		readFilesFromFolder("C1ASCloudConnectorConfig__c", new File(folderName));
//		readFilesFromFolder("CCCLMCONTRACT__CallidusCloudCLMConfiguration__c", new File(folderName));
//		readFilesFromFolder("CCCLMCONTRACT__Related_Contracts__c", new File(folderName));
//		readFilesFromFolder("CLMConfig__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Account_Name_Filter__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__AutoConvert_Mapping__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__AutoConvert_Setting__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__AutoMerge_Mapping__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__AutoMerge_Setting__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Batch_Key_Builder_Data__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Block_Bypass__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Convert_Display_Field__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Country_Mapping__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Duplicate_Warning__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__FirstName_Mapping__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Fuzzy_Rule__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__General_Setting__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Potential_Duplicate__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario_Filter__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario_Key__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario_Link__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario_Rule__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario_Target_Filter__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Scenario__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Setting__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__State_Mapping__c", new File(folderName));
//		readFilesFromFolder("CRMfusionDBR101__Web_Lead_Source__c", new File(folderName));
//		readFilesFromFolder("CTI__c", new File(folderName));
//		readFilesFromFolder("Call_Activity_Report__c", new File(folderName));
//		readFilesFromFolder("Call_Message__c", new File(folderName));
//		readFilesFromFolder("Call_Product__c", new File(folderName));
//		readFilesFromFolder("CampaignMap__c", new File(folderName));
//		readFilesFromFolder("CampaignMemberStatus_Settings__c", new File(folderName));
//		readFilesFromFolder("Campaign_Expense__c", new File(folderName));
//		readFilesFromFolder("Campaign_Tier__c", new File(folderName));
//		readFilesFromFolder("Campaign_Tiers_Latam__c", new File(folderName));
//		readFilesFromFolder("Case_Product__c", new File(folderName));
//		readFilesFromFolder("Case_Settings__c", new File(folderName));
//		readFilesFromFolder("Cegedim_Settings__c", new File(folderName));
//		readFilesFromFolder("Channel_acquisition_picklist__c", new File(folderName));
//		readFilesFromFolder("City__c", new File(folderName));
//		readFilesFromFolder("CoachingMessageByMarket__c", new File(folderName));
//		readFilesFromFolder("Coaching_Agenda__c", new File(folderName));
//		readFilesFromFolder("Coaching_Feedback__c", new File(folderName));
//		readFilesFromFolder("Coaching_Improvement__c", new File(folderName));
//		readFilesFromFolder("Coaching_Report__c", new File(folderName));
//		readFilesFromFolder("Coaching_Strength__c", new File(folderName));
//		readFilesFromFolder("Commercial_Condition__c", new File(folderName));
//		readFilesFromFolder("Contact_Address__c", new File(folderName));
//		readFilesFromFolder("ContractParticipants__c", new File(folderName));
//		readFilesFromFolder("ContractProductRebate__c", new File(folderName));
//		readFilesFromFolder("ContractProduct__c", new File(folderName));
//		readFilesFromFolder("ContractPromotions__c", new File(folderName));
//		readFilesFromFolder("ContractScanDowns__c", new File(folderName));
//		readFilesFromFolder("ContractValidationMatrix__c", new File(folderName));
//		readFilesFromFolder("Copy_Paste_Tool__c", new File(folderName));
//		readFilesFromFolder("Countries__c", new File(folderName));
//		readFilesFromFolder("Country__c", new File(folderName));
//		readFilesFromFolder("Create_Value_Through_Innovation_Meas__c", new File(folderName));
//		readFilesFromFolder("Create_Value_Through_Innovation__c", new File(folderName));
//		readFilesFromFolder("Currency_Code_Settings__c", new File(folderName));
//		readFilesFromFolder("Custom_Exceptions__c", new File(folderName));
//		readFilesFromFolder("CustomerTempTable__c", new File(folderName));
//		readFilesFromFolder("Cycle_Plan_Account_Target__c", new File(folderName));
//		readFilesFromFolder("Cycle_Plan__c", new File(folderName));
//		readFilesFromFolder("DL__c", new File(folderName));
//		readFilesFromFolder("Data_Change_Request__c", new File(folderName));
//		readFilesFromFolder("Details_Pump_Settings__c", new File(folderName));
//		readFilesFromFolder("DeviceWarrantyPeriod__c", new File(folderName));
//		readFilesFromFolder("Device_Owner__c", new File(folderName));
//		readFilesFromFolder("Device__c", new File(folderName));
//		readFilesFromFolder("DispatchNoteInfo__c", new File(folderName));
//		readFilesFromFolder("Distributor__c", new File(folderName));
//		readFilesFromFolder("District__c", new File(folderName));
//		readFilesFromFolder("DoNotReceiveTerritotyEmails__c", new File(folderName));
//		readFilesFromFolder("ERD__ERD_Tool_Object__c", new File(folderName));
//		readFilesFromFolder("ET_CustomerKey__c", new File(folderName));
//		readFilesFromFolder("EmailSmsNotification__c", new File(folderName));
//		readFilesFromFolder("Employment_Website__c", new File(folderName));
//		readFilesFromFolder("EncryptedAddress__c", new File(folderName));
//		readFilesFromFolder("ExactTarget_Integration_Settings__c", new File(folderName));
//		readFilesFromFolder("Excellence_in_Execution_Measurement__c", new File(folderName));
//		readFilesFromFolder("Excellence_in_Execution_for_NAM_KAM__c", new File(folderName));
//		readFilesFromFolder("FOCProduct__c", new File(folderName));
//		readFilesFromFolder("Field_Sales_Collaboration__c", new File(folderName));
//		readFilesFromFolder("Field_Trip__Field_Analysis__c", new File(folderName));
//		readFilesFromFolder("Field_Trip__Logistics__c", new File(folderName));
//		readFilesFromFolder("Field_Trip__Object_Analysis__c", new File(folderName));
//		readFilesFromFolder("Fuzzy_Search_Settings__c", new File(folderName));
//		readFilesFromFolder("GenerateWorkingDays__c", new File(folderName));
//		readFilesFromFolder("GenericData__c", new File(folderName));
//		readFilesFromFolder("GiftBusinessRule__c", new File(folderName));
//		readFilesFromFolder("Global_Reach_Local_Focus_Meas__c", new File(folderName));
//		readFilesFromFolder("Global_Reach_Local_Focus__c", new File(folderName));
//		readFilesFromFolder("Growth_Opportunity__c", new File(folderName));
//		readFilesFromFolder("Help_Documents__c", new File(folderName));
//		readFilesFromFolder("Holiday__c", new File(folderName));
//		readFilesFromFolder("ID_Creating_Value_Through_Innovation__c", new File(folderName));
//		readFilesFromFolder("ID_Excellence_In_Execution__c", new File(folderName));
//		readFilesFromFolder("ID_Lead_With_Purpose__c", new File(folderName));
//		readFilesFromFolder("ID_Leverage_Strategic_Partnerships__c", new File(folderName));
//		readFilesFromFolder("ID_Measure_Creating_Value_Innovation__c", new File(folderName));
//		readFilesFromFolder("ID_Measure_Excellence_In_Execution__c", new File(folderName));
//		readFilesFromFolder("ID_Measure_Lead_With_Purpose__c", new File(folderName));
//		readFilesFromFolder("ID_Measure_Other__c", new File(folderName));
//		readFilesFromFolder("ID_Measure_Strategic_Partnerships__c", new File(folderName));
//		readFilesFromFolder("ID_Others__c", new File(folderName));
//		readFilesFromFolder("ID_Plan__c", new File(folderName));
//		readFilesFromFolder("IDs_List_for_LFS_US__c", new File(folderName));
//		readFilesFromFolder("Implementation_Action__c", new File(folderName));
//		readFilesFromFolder("Improve_Insulin_Del_Share__c", new File(folderName));
//		readFilesFromFolder("Improve_Insulin_Delivery__c", new File(folderName));
//		readFilesFromFolder("Incremental_Account_Growth_Initiatives__c", new File(folderName));
//		readFilesFromFolder("InsurancePlan__c", new File(folderName));
//		readFilesFromFolder("JJDI_Healthy_Engagements_Programs_Meas__c", new File(folderName));
//		readFilesFromFolder("JJDI_Healthy_Engagements__c", new File(folderName));
//		readFilesFromFolder("JJ_SRS_PayerForPayerDashboard__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__Cat_Content_Junction__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__CategoryMobileConfig__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__Category__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__ContentReview__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__DSA_App_Setting__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__DSA_Playlist__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__MobileAppConfig__c", new File(folderName));
//		readFilesFromFolder("JnJDSF4__Playlist_Content_Junction__c", new File(folderName));
//		readFilesFromFolder("Key_Message__c", new File(folderName));
//		readFilesFromFolder("Key_Strategic_Measure__c", new File(folderName));
//		readFilesFromFolder("LATAM_Country_Code_Setting__c", new File(folderName));
//		readFilesFromFolder("LATAM_Portal_Email_Settings__c", new File(folderName));
//		readFilesFromFolder("LATAM_Portal_Setting__c", new File(folderName));
//		readFilesFromFolder("LATAM_Services_Status_Settings__c", new File(folderName));
//		readFilesFromFolder("LFS_Channels_Permission_Setting__c", new File(folderName));
//		readFilesFromFolder("LFS_Patient_Settings__c", new File(folderName));
//		readFilesFromFolder("Lead_with_Purpose_Meas__c", new File(folderName));
//		readFilesFromFolder("Lead_with_Purpose__c", new File(folderName));
//		readFilesFromFolder("Licence_Instance__c", new File(folderName));
//		readFilesFromFolder("Licence_UserLicence__c", new File(folderName));
//		readFilesFromFolder("Licence_Users__c", new File(folderName));
//		readFilesFromFolder("License__c", new File(folderName));
//		readFilesFromFolder("Location__c", new File(folderName));
//		readFilesFromFolder("LogBooksByMarket__c", new File(folderName));
//		readFilesFromFolder("LoyaltyProgramEscalation__c", new File(folderName));
//		readFilesFromFolder("Loyalty_Medication__c", new File(folderName));
//		readFilesFromFolder("MergeSettings__c", new File(folderName));
//		readFilesFromFolder("Merger__c", new File(folderName));
//		readFilesFromFolder("MeterRecallFunction__c", new File(folderName));
//		readFilesFromFolder("Metrics_on_Event__c", new File(folderName));
//		readFilesFromFolder("ModelM__CategoryMobileConfig__c", new File(folderName));
//		readFilesFromFolder("ModelM__Category__c", new File(folderName));
//		readFilesFromFolder("ModelM__ContentReview__c", new File(folderName));
//		readFilesFromFolder("ModelM__MobileAppConfig__c", new File(folderName));
//		readFilesFromFolder("ModelM__iOS_Links__c", new File(folderName));
//		readFilesFromFolder("ModelM__iPad_Content_Views__c", new File(folderName));
//		readFilesFromFolder("NAD_Access_Contracting_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAD_Buying_Influences_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAD_Field_Sales_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAD_Growth__c", new File(folderName));
//		readFilesFromFolder("NAD_Growth_measurement__c", new File(folderName));
//		readFilesFromFolder("NAD_Other_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAD_Other__c", new File(folderName));
//		readFilesFromFolder("NAD_POD_Leadership_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Access_Contracting_Measurements__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Access_Contracting__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Collaboration_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Collaboration__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Customer_Development_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Customer_Development__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Growth_Measurements__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Growth__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Leadership_Measurement__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Leadership__c", new File(folderName));
//		readFilesFromFolder("NAM_KAM_Other_Measurement__c", new File(folderName));
//		readFilesFromFolder("NCSGenericValues__c", new File(folderName));
//		readFilesFromFolder("NCS_Account_Objectives__c", new File(folderName));
//		readFilesFromFolder("NCS_Plan__c", new File(folderName));
//		readFilesFromFolder("NCS_SWOT__c", new File(folderName));
//		readFilesFromFolder("NCS_Team_Member__c", new File(folderName));
//		readFilesFromFolder("Offer_Eligibility__c", new File(folderName));
//		readFilesFromFolder("Offer_Rule__c", new File(folderName));
//		readFilesFromFolder("OrderSettings__c", new File(folderName));
//		readFilesFromFolder("Order_Configuration__c", new File(folderName));
//		readFilesFromFolder("Order_Pricebook__c", new File(folderName));
//		readFilesFromFolder("Other__c", new File(folderName));
//		readFilesFromFolder("POD_Leadership__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_Address_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_Detail_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_Professions_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_SLN_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_Specialty_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Account_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Parameter_ims__c", new File(folderName));
//		readFilesFromFolder("PVS_Search_Criteria_ims__c", new File(folderName));
//		readFilesFromFolder("Participant__c", new File(folderName));
//		readFilesFromFolder("Patient_Guardian__c", new File(folderName));
//		readFilesFromFolder("Patient__c", new File(folderName));
//		readFilesFromFolder("PaymentProduct__c", new File(folderName));
//		readFilesFromFolder("Pharmacy__c", new File(folderName));
//		readFilesFromFolder("Plan_Financial_Data__c", new File(folderName));
//		readFilesFromFolder("Plan__c", new File(folderName));
//		readFilesFromFolder("PlanningPeriods__c", new File(folderName));
//		readFilesFromFolder("Postcode_Eligibility__c", new File(folderName));
//		readFilesFromFolder("Pre_Pump_Assessment_Questionnaire__c", new File(folderName));
//		readFilesFromFolder("Price_Book_Relation__c", new File(folderName));
//		readFilesFromFolder("ProductRebate__c", new File(folderName));
//		readFilesFromFolder("ProductRegistration__c", new File(folderName));
//		readFilesFromFolder("ProductSerialNumberValidation__c", new File(folderName));
//		readFilesFromFolder("Product_Offer__c", new File(folderName));
//		readFilesFromFolder("Product_Reservation__c", new File(folderName));
//		readFilesFromFolder("ProductsSelfReported__c", new File(folderName));
//		readFilesFromFolder("Project_Deliverable__c", new File(folderName));
//		readFilesFromFolder("Project_Issue__c", new File(folderName));
//		readFilesFromFolder("Project_Plan__c", new File(folderName));
//		readFilesFromFolder("Project_Product_Issue__c", new File(folderName));
//		readFilesFromFolder("Project_Product__c", new File(folderName));
//		readFilesFromFolder("Project_Production_Change__c", new File(folderName));
//		readFilesFromFolder("Project_Release__c", new File(folderName));
//		readFilesFromFolder("Project_Report__c", new File(folderName));
//		readFilesFromFolder("Project_Risk__c", new File(folderName));
//		readFilesFromFolder("Project_Task__c", new File(folderName));
//		readFilesFromFolder("Project__c", new File(folderName));
//		readFilesFromFolder("PromotionPayment__c", new File(folderName));
//		readFilesFromFolder("Promotion_Item__c", new File(folderName));
//		readFilesFromFolder("Promotion_Payment_ToAddress__c", new File(folderName));
//		readFilesFromFolder("Promotion_Product__c", new File(folderName));
//		readFilesFromFolder("Promotion_Rule_Group__c", new File(folderName));
//		readFilesFromFolder("Promotion_Rule_Mapping__c", new File(folderName));
//		readFilesFromFolder("Promotion_Rule__c", new File(folderName));
//		readFilesFromFolder("Promotion_Transaction__c", new File(folderName));
//		readFilesFromFolder("Pump_Sales__c", new File(folderName));
//		readFilesFromFolder("Pump_Settings__c", new File(folderName));
//		readFilesFromFolder("RebateDetail__c", new File(folderName));
//		readFilesFromFolder("Rebate__c", new File(folderName));
//		readFilesFromFolder("Recall_Approval__c", new File(folderName));
//		readFilesFromFolder("RedemptionTempTable__c", new File(folderName));
//		readFilesFromFolder("ReturnDevice__c", new File(folderName));
//		readFilesFromFolder("Return__c", new File(folderName));
//		readFilesFromFolder("Role__c", new File(folderName));
//		readFilesFromFolder("RollUp_Fields__c", new File(folderName));
//		readFilesFromFolder("SDOC__SDField__c", new File(folderName));
//		readFilesFromFolder("SDOC__SDRelationship__c", new File(folderName));
//		readFilesFromFolder("SDOC__SDTemplate__c", new File(folderName));
//		readFilesFromFolder("SDOC__SDoc__c", new File(folderName));
//		readFilesFromFolder("SDOC__SDocsSettings__c", new File(folderName));
//		readFilesFromFolder("SFGA__Ad_Group__c", new File(folderName));
//		readFilesFromFolder("SFGA__Google_Campaign__c", new File(folderName));
//		readFilesFromFolder("SFGA__Keyword__c", new File(folderName));
//		readFilesFromFolder("SFGA__Search_Phrase__c", new File(folderName));
//		readFilesFromFolder("SFGA__Text_Ad__c", new File(folderName));
//		readFilesFromFolder("SFGA__Version_33_0_3__c", new File(folderName));
//		readFilesFromFolder("SMD_AC_Measurement__c", new File(folderName));
//		readFilesFromFolder("SMD_Access_and_Contracting__c", new File(folderName));
//		readFilesFromFolder("SMD_BIC_Measurement__c", new File(folderName));
//		readFilesFromFolder("SMD_Buying_Influences_Customer_Meeting__c", new File(folderName));
//		readFilesFromFolder("SMD_FSC_Measurement__c", new File(folderName));
//		readFilesFromFolder("SMD_Field_Sales_Collaboration__c", new File(folderName));
//		readFilesFromFolder("SMD_G_Measurement__c", new File(folderName));
//		readFilesFromFolder("SMD_Growth__c", new File(folderName));
//		readFilesFromFolder("SMD_O_Measurement__c", new File(folderName));
//		readFilesFromFolder("SMD_Other__c", new File(folderName));
//		readFilesFromFolder("SPOInsurancePlan__c", new File(folderName));
//		readFilesFromFolder("Secure_Contracts_Measurement__c", new File(folderName));
//		readFilesFromFolder("Secure_Contracts__c", new File(folderName));
//		readFilesFromFolder("Service_Integration_Settings__c", new File(folderName));
//		readFilesFromFolder("Shelf_Detail_Line__c", new File(folderName));
//		readFilesFromFolder("Shelf_Detail__c", new File(folderName));
//		readFilesFromFolder("SpecialPromotionDCL__c", new File(folderName));
//		readFilesFromFolder("State_Province__c", new File(folderName));
//		readFilesFromFolder("Survey2Answer__c", new File(folderName));
//		readFilesFromFolder("Survey2__c", new File(folderName));
//		readFilesFromFolder("Survey_Test__c", new File(folderName));
//		readFilesFromFolder("Survey__c", new File(folderName));
//		readFilesFromFolder("Tender_Award_Result__c", new File(folderName));
//		readFilesFromFolder("Tender_Evaluation_Criteria__c", new File(folderName));
//		readFilesFromFolder("Tender_Technical_Spec__c", new File(folderName));
//		readFilesFromFolder("TerritoryManagement__c", new File(folderName));
//		readFilesFromFolder("Test_Script__c", new File(folderName));
//		readFilesFromFolder("Test__c", new File(folderName));
//		readFilesFromFolder("Training_Certification__c", new File(folderName));
//		readFilesFromFolder("Training_History__c", new File(folderName));
//		readFilesFromFolder("Training_Task__c", new File(folderName));
//		readFilesFromFolder("Training__c", new File(folderName));
//		readFilesFromFolder("Transaction__c", new File(folderName));
//		readFilesFromFolder("TriggerDisabler__c", new File(folderName));
//		readFilesFromFolder("TwentyOneDaysEnabled__c", new File(folderName));
//		readFilesFromFolder("TwentyOneDaysTimes__c", new File(folderName));
//		readFilesFromFolder("TwentyoneDaysBooks__c", new File(folderName));
//		readFilesFromFolder("USDigitalMarketingGifts__c", new File(folderName));
//		readFilesFromFolder("USStatesCode__c", new File(folderName));
//		readFilesFromFolder("Update_Request__c", new File(folderName));
//		readFilesFromFolder("ValidationDate__c", new File(folderName));
//		readFilesFromFolder("ValidationSettings__c", new File(folderName));
//		readFilesFromFolder("ValuesPickListViewActivities__c", new File(folderName));
//		readFilesFromFolder("Visit_Invitees__c", new File(folderName));
//		readFilesFromFolder("Visit_Product__c", new File(folderName));
//		readFilesFromFolder("Visit__c", new File(folderName));
//		readFilesFromFolder("WebToLeadType__c", new File(folderName));
//		readFilesFromFolder("Web_Order_Product__c", new File(folderName));
//		readFilesFromFolder("Workflow_Disabler__c", new File(folderName));
//		readFilesFromFolder("YearlyForecast__c", new File(folderName));
//		readFilesFromFolder("eMapandpMap__c", new File(folderName));
//		readFilesFromFolder("et4ae5__AggregateLink__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Automated_Send__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Business_Unit__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Campaign_Member_Configuration__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Configuration__c", new File(folderName));
//		readFilesFromFolder("et4ae5__ET4AEConfig__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Email_Linkage__c", new File(folderName));
//		readFilesFromFolder("et4ae5__IndividualEmailResult__c", new File(folderName));
//		readFilesFromFolder("et4ae5__IndividualLink__c", new File(folderName));
//		readFilesFromFolder("et4ae5__SMSDefinition__c", new File(folderName));
//		readFilesFromFolder("et4ae5__SMSJunction__c", new File(folderName));
//		readFilesFromFolder("et4ae5__SendDefinition__c", new File(folderName));
//		readFilesFromFolder("et4ae5__SendJunction__c", new File(folderName));
//		readFilesFromFolder("et4ae5__SupportRequest__c", new File(folderName));
//		readFilesFromFolder("et4ae5__Triggered_Send_Execution__c", new File(folderName));
//		readFilesFromFolder("et4ae5__UEBU__c", new File(folderName));
//		readFilesFromFolder("et4ae5__abTest__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpBookmark__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpInteraction__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpReadingListEntry__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpReadingList__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpRelationship__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpResource__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpTopicResource__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpTopicTemplate__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpTopic__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpableSignature__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpedElement__c", new File(folderName));
//		readFilesFromFolder("iahelp__HelpedPageLayout__c", new File(folderName));
//		readFilesFromFolder("iahelp__IASetIHOrg__c", new File(folderName));
//		readFilesFromFolder("pca__Action__c", new File(folderName));
//		readFilesFromFolder("pca__Address__c", new File(folderName));
//		readFilesFromFolder("pca__Business__c", new File(folderName));
//		readFilesFromFolder("pca__Email_Integration__c", new File(folderName));
//		readFilesFromFolder("pca__Payment_Integration__c", new File(folderName));
//		readFilesFromFolder("pca__PostcodeAnywhereAddresses__c", new File(folderName));
//		readFilesFromFolder("pca__PostcodeAnywhereCountries__c", new File(folderName));
//		readFilesFromFolder("pca__PostcodeAnywhereFields__c", new File(folderName));
//		readFilesFromFolder("pca__PostcodeAnywhereSettings__c", new File(folderName));
//		readFilesFromFolder("pca__Setting__c", new File(folderName));
//		readFilesFromFolder("xtma_Email_Result__c", new File(folderName));
//		readFilesFromFolder("xtma_Individual_Email_Result__c", new File(folderName));
//		readFilesFromFolder("xtma_Link_Detail__c", new File(folderName));

		//generate result.csv and resultFlat.csv
		writeToCsv(folderName);
		writeToCsvFlat(folderName);
	}

}
